services:
  db_ci:
    image: postgres
    container_name: db_ci
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test
    volumes:
      - pg:/var/lib/postgresql/data

  node_app_ci:
    container_name: node_app_ci
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - db_ci

volumes:
  pg: